language: python
sudo: false
matrix:
  include:
    - python: 2.7
      arch: amd64
    - python: 3.5
      arch: amd64
    - python: 3.6
      arch: amd64
    - python: 3.7
      arch: amd64
    - python: 2.7
      arch: ppc64le
    - python: 3.5
      arch: ppc64le
    - python: 3.6
      arch: ppc64le
    - python: 3.7
      arch: ppc64le
  fast_finish: true
addons:
  apt:
    packages:
      - libxmlsec1-dev
      - swig
install:
  - pip install tox tox-travis -U pip
script:
  - tox
